package com.genir.renderer.loaders;

import com.fs.starfarer.loading.JavaSourceFinder;
import org.codehaus.janino.JavaSourceClassLoader;
import org.codehaus.janino.util.resource.ResourceFinder;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

public class MultiThreadedJavaSourceClassLoader extends ClassLoader {
    private final Map<Thread, JavaSourceCompiler> compilers = new ConcurrentHashMap<>();

    static {
        // Marks this class loader type as parallel-capable
        registerAsParallelCapable();
    }

    public MultiThreadedJavaSourceClassLoader(ClassLoader parent) {
        super(parent);
    }

    @Override
    public Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
        synchronized (getClassLoadingLock(name)) {
            // Delegate to parent.
            try {
                return super.getParent().loadClass(name);
            } catch (ClassNotFoundException ignored) {
            }

            // Return previously loaded class.
            Class<?> loaded = findLoadedClass(name);
            if (loaded != null) {
                return loaded;
            }

            return findClass(name);
        }
    }

    @Override
    public Class<?> findClass(String name) throws ClassNotFoundException {
        JavaSourceCompiler compiler = compilers.computeIfAbsent(Thread.currentThread(), k -> new JavaSourceCompiler(new RecursiveClassLoader(this)));

        Map<String, byte[]> bytecodes = compiler.generateBytecodes(name);
        byte[] bytecode = bytecodes.get(name);

        return defineClass(name, bytecode, 0, bytecode.length);
    }

    private static class JavaSourceCompiler extends JavaSourceClassLoader {
        RecursiveClassLoader parent;

        JavaSourceCompiler(RecursiveClassLoader parent) {
            super(parent, parent.resourceFinder, "UTF-8");
            super.setDebuggingInfo(true, true, true);

            this.parent = parent;
        }

        @Override
        protected Map<String, byte[]> generateBytecodes(String name) throws ClassNotFoundException {
            parent.currentlyLoading = name;
            try {
                return super.generateBytecodes(name);
            } finally {
                parent.currentlyLoading = null;
            }
        }
    }

    private static class RecursiveClassLoader extends ClassLoader {
        String currentlyLoading = null;
        ResourceFinder resourceFinder = new JavaSourceFinder();

        RecursiveClassLoader(ClassLoader parent) {
            super(parent);
        }

        @Override
        public Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
            // Break recursion.
            if (name != null && name.equals(currentlyLoading)) {
                throw new ClassNotFoundException();
            }

            ClassLoader scriptLoader = super.getParent();
            ClassLoader jarLoader = scriptLoader.getParent();

            // Try to find the dependency in compiled
            // scripts or in the application.
            try {
                return jarLoader.loadClass(name);
            } catch (ClassNotFoundException ignored) {
            }

            // Handle malformed names generated by Janino.
            if (resourceFinder.findResource(name) == null) {
                throw new ClassNotFoundException();
            }

            // Delegate to script loader, potentially
            // triggering recursive compilation.
            return scriptLoader.loadClass(name);
        }
    }
}
