package com.genir.renderer.loaders;

import com.fs.starfarer.loading.JavaSourceFinder;
import org.codehaus.janino.JavaSourceClassLoader;
import org.codehaus.janino.util.resource.ResourceFinder;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * MultiThreadedJavaSourceClassLoader is a parallel capable wrapper around Janino ClassLoader.
 */
public class MultiThreadedJavaSourceClassLoader extends ClassLoader {
    private final Map<Thread, JavaSourceCompiler> compilers = new ConcurrentHashMap<>();

    static {
        // Marks this class loader type as parallel-capable
        registerAsParallelCapable();
    }

    public MultiThreadedJavaSourceClassLoader(ClassLoader parent) {
        super(parent);
    }

    @Override
    public Class<?> findClass(String name) throws ClassNotFoundException {
        // Allocate a separate Janino instance for each thread.
        JavaSourceCompiler compiler = compilers.computeIfAbsent(Thread.currentThread(), k -> {
            return new JavaSourceCompiler(new RecursiveClassLoader(this));
        });

        // Use Janino to compile the Java source, but not to define the class.
        Map<String, byte[]> bytecodes = compiler.generateBytecodes(name);
        if (bytecodes == null) {
            throw new ClassNotFoundException();
        }

        // All compiled classes are defined by MultiThreadedJavaSourceClassLoader,
        // not the individual Janino instances.
        byte[] bytecode = bytecodes.get(name);
        return defineClass(name, bytecode, 0, bytecode.length);
    }

    // A wrapper around Janino ClassLoader that makes bytecode generation accessible.
    private static class JavaSourceCompiler extends JavaSourceClassLoader {
        RecursiveClassLoader parent;

        JavaSourceCompiler(RecursiveClassLoader parent) {
            super(parent, parent.resourceFinder, "UTF-8");
            super.setDebuggingInfo(true, true, true);

            this.parent = parent;
        }

        @Override
        protected Map<String, byte[]> generateBytecodes(String name) throws ClassNotFoundException {
            parent.currentlyLoading = name;
            try {
                return super.generateBytecodes(name);
            } finally {
                parent.currentlyLoading = null;
            }
        }
    }

    // A wrapper around Janino parent ClassLoader. The wrapper ensures recursive code compilation called
    // by Janino is intercepted and correctly handled by MultiThreadedJavaSourceClassLoader.
    private static class RecursiveClassLoader extends ClassLoader {
        String currentlyLoading = null;
        ResourceFinder resourceFinder = new JavaSourceFinder();

        RecursiveClassLoader(ClassLoader parent) {
            super(parent);
        }

        @Override
        public Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
            // When generating bytecode, Janino will first try to load the class
            // through the parent ClassLoader. Since parent is the same
            // MultiThreadedJavaSourceClassLoader that triggered the bytecode
            // generation, it is necessary to break the recursion.
            if (name != null && name.equals(currentlyLoading)) {
                throw new ClassNotFoundException();
            }

            ClassLoader scriptLoader = super.getParent();
            ClassLoader jarLoader = scriptLoader.getParent();

            // Try to find the dependency in compiled
            // scripts or in starsector-core.
            try {
                return jarLoader.loadClass(name);
            } catch (ClassNotFoundException ignored) {
            }

            // Handle malformed class names generated by Janino. This step is required,
            // because vanilla resource finder will return a non-null resource for some
            // of the malformed names. This in turn leads to recursive bytecode generation
            // attempt and java.lang.ClassCircularityError.
            if (resourceFinder.findResource(name) == null || !name.contains(".")) {
                throw new ClassNotFoundException();
            }

            // The class is not part of starsector-core or compiled jars.
            // It's either Janino code or a missing class. Delegate to script
            // loader, potentially triggering a recursive Janino compilation.
            return scriptLoader.loadClass(name);
        }
    }
}
