rm -rf                         "$SS_PATH/starsector-core/fr.jar"
rm -rf                         "$SS_PATH/starsector-core/fr.agent.jar"
rm -rf                         "$SS_PATH/starsector-core/fr.bat"
rm -rf                         "$SS_PATH/starsector-core/fr.noterminal.bat"
rm -rf                         "$SS_PATH/starsector-core/fr.vmparams"

cp ./jars/final/fr.jar         "$SS_PATH/starsector-core/fr.jar"
cp ./jars/compile/fr.agent.jar "$SS_PATH/starsector-core/fr.agent.jar"
cp ./fr.bat                    "$SS_PATH/starsector-core/fr.bat"
cp ./fr.terminal.bat           "$SS_PATH/starsector-core/fr.noterminal.bat"
cp ./fr.vmparams               "$SS_PATH/starsector-core/fr.vmparams"
