#!/bin/bash

rm -rf ./assembly/bridged
cp -R ./disassembly/starfarer assembly/bridged

find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDisable ^invokestatic Method com/genir/graphics/GLBridge glDisable ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glEnable ^invokestatic Method com/genir/graphics/GLBridge glEnable ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glBlendFunc ^invokestatic Method com/genir/graphics/GLBridge glBlendFunc ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glBegin ^invokestatic Method com/genir/graphics/GLBridge glBegin ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glEnd ^invokestatic Method com/genir/graphics/GLBridge glEnd ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glHint ^invokestatic Method com/genir/graphics/GLBridge glHint ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glVertex2f ^invokestatic Method com/genir/graphics/GLBridge glVertex2f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPushMatrix ^invokestatic Method com/genir/graphics/GLBridge glPushMatrix ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPopMatrix ^invokestatic Method com/genir/graphics/GLBridge glPopMatrix ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTranslatef ^invokestatic Method com/genir/graphics/GLBridge glTranslatef ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColor4ub ^invokestatic Method com/genir/graphics/GLBridge glColor4ub ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glScalef ^invokestatic Method com/genir/graphics/GLBridge glScalef ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColorMask ^invokestatic Method com/genir/graphics/GLBridge glColorMask ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glRotatef ^invokestatic Method com/genir/graphics/GLBridge glRotatef ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexCoord2f ^invokestatic Method com/genir/graphics/GLBridge glTexCoord2f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glLineWidth ^invokestatic Method com/genir/graphics/GLBridge glLineWidth ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glStencilFunc ^invokestatic Method com/genir/graphics/GLBridge glStencilFunc ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDeleteTextures ^invokestatic Method com/genir/graphics/GLBridge glDeleteTextures ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPolygonMode ^invokestatic Method com/genir/graphics/GLBridge glPolygonMode ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glGetInteger ^invokestatic Method com/genir/graphics/GLBridge glGetInteger ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glViewport ^invokestatic Method com/genir/graphics/GLBridge glViewport ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glGetString ^invokestatic Method com/genir/graphics/GLBridge glGetString ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glFlush ^invokestatic Method com/genir/graphics/GLBridge glFlush ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glFinish ^invokestatic Method com/genir/graphics/GLBridge glFinish ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glScissor ^invokestatic Method com/genir/graphics/GLBridge glScissor ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glStencilOp ^invokestatic Method com/genir/graphics/GLBridge glStencilOp ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glAlphaFunc ^invokestatic Method com/genir/graphics/GLBridge glAlphaFunc ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glReadPixels ^invokestatic Method com/genir/graphics/GLBridge glReadPixels ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glGenTextures ^invokestatic Method com/genir/graphics/GLBridge glGenTextures ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexParameteri ^invokestatic Method com/genir/graphics/GLBridge glTexParameteri ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPointSize ^invokestatic Method com/genir/graphics/GLBridge glPointSize ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glShadeModel ^invokestatic Method com/genir/graphics/GLBridge glShadeModel ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glLight ^invokestatic Method com/genir/graphics/GLBridge glLight ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glMaterial ^invokestatic Method com/genir/graphics/GLBridge glMaterial ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glMateriali ^invokestatic Method com/genir/graphics/GLBridge glMateriali ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColor3ub ^invokestatic Method com/genir/graphics/GLBridge glColor3ub ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glNormal3f ^invokestatic Method com/genir/graphics/GLBridge glNormal3f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glVertex3d ^invokestatic Method com/genir/graphics/GLBridge glVertex3d ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColor3d ^invokestatic Method com/genir/graphics/GLBridge glColor3d ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexEnvf ^invokestatic Method com/genir/graphics/GLBridge glTexEnvf ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColor4f ^invokestatic Method com/genir/graphics/GLBridge glColor4f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glMatrixMode ^invokestatic Method com/genir/graphics/GLBridge glMatrixMode ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glLoadIdentity ^invokestatic Method com/genir/graphics/GLBridge glLoadIdentity ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glIsEnabled ^invokestatic Method com/genir/graphics/GLBridge glIsEnabled ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glBindTexture ^invokestatic Method com/genir/graphics/GLBridge glBindTexture ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexImage2D ^invokestatic Method com/genir/graphics/GLBridge glTexImage2D ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexSubImage2D ^invokestatic Method com/genir/graphics/GLBridge glTexSubImage2D ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTexCoordPointer ^invokestatic Method com/genir/graphics/GLBridge glTexCoordPointer ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColorPointer ^invokestatic Method com/genir/graphics/GLBridge glColorPointer ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glVertex3f ^invokestatic Method com/genir/graphics/GLBridge glVertex3f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColorMaterial ^invokestatic Method com/genir/graphics/GLBridge glColorMaterial ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glColor3f ^invokestatic Method com/genir/graphics/GLBridge glColor3f ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glVertexPointer ^invokestatic Method com/genir/graphics/GLBridge glVertexPointer ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDrawArrays ^invokestatic Method com/genir/graphics/GLBridge glDrawArrays ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glOrtho ^invokestatic Method com/genir/graphics/GLBridge glOrtho ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glClear ^invokestatic Method com/genir/graphics/GLBridge glClear ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glClearColor ^invokestatic Method com/genir/graphics/GLBridge glClearColor ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPushAttrib ^invokestatic Method com/genir/graphics/GLBridge glPushAttrib ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glPopAttrib ^invokestatic Method com/genir/graphics/GLBridge glPopAttrib ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glCallList ^invokestatic Method com/genir/graphics/GLBridge glCallList ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glGenLists ^invokestatic Method com/genir/graphics/GLBridge glGenLists ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glNewList ^invokestatic Method com/genir/graphics/GLBridge glNewList ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glVertexPointer ^invokestatic Method com/genir/graphics/GLBridge glVertexPointer ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDeleteLists ^invokestatic Method com/genir/graphics/GLBridge glDeleteLists ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glInterleavedArrays ^invokestatic Method com/genir/graphics/GLBridge glInterleavedArrays ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glArrayElement ^invokestatic Method com/genir/graphics/GLBridge glArrayElement ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDrawElements ^invokestatic Method com/genir/graphics/GLBridge glDrawElements ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glTranslated ^invokestatic Method com/genir/graphics/GLBridge glTranslated ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glEnableClientState ^invokestatic Method com/genir/graphics/GLBridge glEnableClientState ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glMultMatrix ^invokestatic Method com/genir/graphics/GLBridge glMultMatrix ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glEndList ^invokestatic Method com/genir/graphics/GLBridge glEndList ^g' {} +
find ./assembly/bridged -type f -exec sed -i 's^invokestatic Method org/lwjgl/opengl/GL11 glDisableClientState ^invokestatic Method com/genir/graphics/GLBridge glDisableClientState ^g' {} +